#ifndef __CXPACKETCODEDEFINE_H__
#define __CXPACKETCODEDEFINE_H__

#define CX_SESSION_LOGIN_CODE          1
#define CX_SESSION_LOGIN_REPLY_CODE    2

#define CX_SESSION_LOGOUT_CODE         3
#define CX_SESSION_LOGOUT_REPLY_CODE   4

#define CX_SESSION_SETITING_CODE       5
#define CX_SESSION_SETITING_REPLY_CODE 6

#define CX_HEAERT_BEAT_CODE            7
#define CX_HEAERT_BEAT_REPLY_CODE      8

#define CX_FILE_OPEN_CODE              2001
#define CX_FILE_OPEN_REPLY_CODE        2002

#define CX_FILE_SEEK_CODE              2003
#define CX_FILE_SEEK_REPLY_CODE        2004

#define CX_FILE_READ_CODE              2005
#define CX_FILE_READ_REPLY_CODE        2006

#define CX_FILE_WRITE_CODE             2007
#define CX_FILE_WRITE_REPLY_CODE       2008

#define CX_FILE_CLOSE_CODE             2009
#define CX_FILE_CLOSE_REPLY_CODE       2010

#define CX_FILE_GET_LENGTH_CODE        2011
#define CX_FILE_GET_LENGTH_REPLY_CODE  2012

#endif //__CXPACKETCODEDEFINE_H__